# .github/workflows/build-xcframework.yml
name: Build Custom Matrix SDK

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      # Шаг 1: Клонирование и модификация исходного кода
      - name: Clone and modify matrix-rust-sdk
        working-directory: ./../
        run: |
          # Клонируем репозиторий
          git clone https://github.com/matrix-org/matrix-rust-sdk.git
          cd matrix-rust-sdk
          
          # Модифицируем файл
          perl -i -pe '
            BEGIN { $/ = undef; }
            s{
              if\s+self\.is_direct\(\)\.await\.unwrap_or\(false\)\s*\{\s*
              NotifyType::Ring\s*
              \}\s*
              else\s*
              \{\s*
              NotifyType::Notify\s*
              \}
            }{NotifyType::Ring}gsx;
          ' crates/matrix-sdk/src/room/mod.rs
          
          # Проверяем изменения
          git diff crates/matrix-sdk/src/room/mod.rs || echo "Changes applied"

      # Шаг 2: Настройка Rust
      - name: Setup Rust
        run: |
          echo "Using pre-installed Rust: $(rustc --version)"
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios aarch64-apple-darwin x86_64-apple-darwin

      # Шаг 3: Кэширование зависимостей Rust
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('matrix-rust-sdk/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Шаг 4: Генерация версии
      - name: Generate version
        id: version
        working-directory: ./../matrix-rust-sdk
        run: |
          DATE_VERSION="v1.0.0-withring-$(date +%Y%m%d-%H%M)"
          echo "version=${DATE_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${DATE_VERSION}"

      # Шаг 5: Сборка XCFramework
      - name: Build XCFramework
        working-directory: ./
        run: |
          echo "current dir: $(pwd)"
          echo "current dir: $(ls)"
          cd ..
          echo "current dir: $(pwd)"
          echo "current dir: $(ls)"
          swift run --package-path ./matrix-rust-components-swift/Tools/Release release --version ${{ steps.version.outputs.version }}
