# .github/workflows/build-xcframework.yml
name: Build Custom Matrix SDK

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      # Шаг 1: Клонирование и модификация исходного кода
      - name: Clone and modify matrix-rust-sdk
        working-directory: ./../
        run: |
          # Клонируем репозиторий
          git clone https://github.com/matrix-org/matrix-rust-sdk.git
          cd matrix-rust-sdk
          
          # Модифицируем файл
          sed -i '' 's/if self\.is_direct().await.unwrap_or(false) {.*NotifyType::Notify.*}/NotifyType::Ring,/g' crates/matrix-sdk/src/room/mod.rs
          
          # Проверяем изменения
          git diff crates/matrix-sdk/src/room/mod.rs || echo "Changes applied"

      # Шаг 2: Настройка Rust
      - name: Setup Rust
        run: |
          echo "Using pre-installed Rust: $(rustc --version)"
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios aarch64-apple-darwin

      # Шаг 3: Кэширование зависимостей Rust
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('matrix-rust-sdk/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Шаг 4: Генерация версии
      - name: Generate version
        id: version
        working-directory: ./matrix-rust-sdk
        run: |
          DATE_VERSION="v1.0.18-custom-$(date +%Y%m%d)"
          echo "version=${DATE_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${DATE_VERSION}"

      # Шаг 5: Сборка XCFramework
      - name: Build XCFramework
        working-directory: ./
        run: |
          echo "current dir: $(pwd)"
          echo "current dir: $(ls)"
          cd ..
          echo "current dir: $(pwd)"
          echo "current dir: $(ls)"
          swift run --package-path ./matrix-rust-components-swift/Tools/Release release --version v1.0.18-custom-20250423

      # Шаг 6: Обновление Package.swift
      - name: Update Package.swift
        working-directory: ./matrix-rust-sdk
        run: |
          NEW_CHECKSUM=$(swift package compute-checksum MatrixSDKFFI.xcframework.zip)
          sed -i '' "s/checksum = \".*\"/checksum = \"$NEW_CHECKSUM\"/g" Package.swift
          sed -i '' "s|version = \".*\"|version = \"${{ steps.version.outputs.version }}\"|g" Package.swift
          cat Package.swift

      # Шаг 7: Коммит и пуш изменений
      - name: Commit and push changes
        working-directory: ./matrix-rust-sdk
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Package.swift
          git commit -m "Update XCFramework to ${{ steps.version.outputs.version }}"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/hek4ek/matrix-rust-sdk.git main
